CONFIG = {
    "CAMERA_INDEX": 0,
    "FRAME_WIDTH": 1280,
    "FRAME_HEIGHT": 720,
    "FPS": 30,
    "MAX_LOST_FRAMES": 30,

    "MIN_DETECTION_CONFIDENCE": 0.7,
    "MIN_TRACKING_CONFIDENCE": 0.5,

    "FINGER_EXTENDED_ANGLE": 150,
    "FINGER_PARTIAL_BEND_ANGLE": 100,
    "OK_SIGN_DISTANCE": 0.05,

    "DEADZONE_THRESHOLD": 0.003,
    "DEBOUNCE_FRAMES": 3,
    "DOUBLE_CLICK_WINDOW_SEC": 0.3,
    "CLICK_HOLD_THRESHOLD_SEC": 0.3,
    "FIST_HOLD_SEC": 1.5,

    "CURSOR_DEADZONE": 0.002,
    "CURSOR_SENSITIVITY_X": 2.0,
    "CURSOR_SENSITIVITY_Y": 3.0,

    "ONE_EURO_MIN_CUTOFF": 1.0,
    "ONE_EURO_BETA": 0.01,
    "ONE_EURO_DCUTOFF": 1.0,

    "SHOW_DEBUG_WINDOW": True,
    "PRINT_STATE_CHANGES": True,

    "FLASK_HOST": "127.0.0.1",
    "FLASK_PORT": 5000,

    "DIP_CLICK_THRESHOLD": 0.05,
    "MIDDLE_DIP_CLICK_THRESHOLD": 0.05,
    "SCROLL_SPEED": 15,
    "SCROLL_TOUCH_THRESHOLD": 0.05,
    "SCROLL_DOWN_TOUCH_THRESHOLD": 0.05,
    "SCROLL_UP_TOUCH_THRESHOLD": 0.1,
    "SCROLL_HOLD_SEC": 0.3,
    "USE_ABSOLUTE_MAPPING": True,
    "MOVEMENT_DEADZONE_PIXELS": 15,
    "CURSOR_LANDMARK": 9,
    "INVERT_X": False,
    "INDEX_TIP_MCP_THRESHOLD": 0.07,
    "RING_DIP_CLICK_THRESHOLD": 0.05,
}
