CONFIG = {
    "CAMERA_INDEX": 0,
    "FRAME_WIDTH": 1280,
    "FRAME_HEIGHT": 960,
    "FPS": 60,
    "MAX_LOST_FRAMES": 30,

    "MIN_DETECTION_CONFIDENCE": 0.7,
    "MIN_TRACKING_CONFIDENCE": 0.5,

    "PINCH_THRESHOLD": 0.05,
    "THREE_PINCH_THRESHOLD": 0.06,
    "DOUBLE_CLICK_THRESHOLD": 0.05,
    "OPEN_THRESHOLD": 0.09,
    "SCROLL_EXIT_THRESHOLD": 0.10,
    "CURSOR_DEADZONE": 0.002,

    "DRAG_HOLD_SEC": 0.5,
    "FIST_HOLD_SEC": 1.5,

    "CURSOR_SENSITIVITY": 2.0,
    "SCROLL_SENSITIVITY": 20.0,

    "ONE_EURO_MIN_CUTOFF": 1.0,
    "ONE_EURO_BETA": 0.007,
    "ONE_EURO_DCUTOFF": 1.0,

    "SHOW_DEBUG_WINDOW": True,
    "PRINT_STATE_CHANGES": True,
}